package com.deyvidjgv.inventario.domain.exception;

public enum ErrorCode {
    PRODUCT_NOT_FOUND,
    PRODUCT_INACTIVE,
    CATEGORY_NOT_FOUND,
    INVALID_SALE_PRICE,
    INVALID_QUANTITY,
    INVALID_UNIT_COST,
    MISSING_UNIT_COST,
    INSUFFICIENT_STOCK,
    NO_OPEN_JORNADA,
    JORNADA_ALREADY_OPEN,
    NO_CLOSED_JORNADA_TO_REOPEN,
    JORNADA_NOT_FOUND,
    SALE_NOT_FOUND,
    SALE_ALREADY_VOIDED,
    LOT_NOT_FOUND,
    EXPENSE_NOT_FOUND,
    INVALID_AMOUNT,
    BACKUP_CORRUPTED,
    TRANSACTION_FAILED
}
